# Uploading tester for tcms work

name: End to end tests for end to end tests testing upload test.
on: push
jobs:
   upload:
      name: Upload
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v3
         - name: Activate plugin
           uses: vector-im/kiwitcms-upload-action@main
           with:
              file-pattern: ./junit-files/*.xml
              kiwi-username: ${{ secrets.TCMS_USERNAME }}
              kiwi-password: ${{ secrets.TCMS_PASSWORD }}
              product: "Element Web"
              product-version: "main"
              build-id: ${{ github.sha }}
              suite-name: "Cypress E2E"
              summary-template: '$name'
